# Application Configuration
spring.application.name=Asmitha Explores Bookstore

#server.address=0.0.0.0

# Server Configuration ? Render injects PORT env variable
server.port=${PORT:8080}

# Thymeleaf Configuration
spring.thymeleaf.cache=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Disable DevTools in production
spring.devtools.restart.enabled=false
